#!/bin/bash

# Template the php-fpm.conf file with the environment variables
sed -ie "s|^user =.*$|user = ${USER}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^group =.*$|group = ${GROUP}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^listen =.*$|listen = ${LISTEN}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^pm\.max_children =.*$|pm\.max_children = ${PM_MAX_CHILDREN}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^pm\.start_servers =.*$|pm\.start_servers = ${PM_START_SERVERS}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^pm\.min_spare_servers =.*$|pm\.min_spare_servers = ${PM_MIN_SPARE_SERVERS}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^pm\.max_spare_servers =.*$|pm\.max_spare_servers = ${PM_MAX_SPARE_SERVERS}|g" /usr/local/etc/php-fpm.conf
sed -ie "s|^pm\.max_requests =.*$|pm\.max_requests = ${PM_MAX_REQUESTS}|g" /usr/local/etc/php-fpm.conf

# Template New Relic PHP module configuration
sed -ie "s|^newrelic.license =.*$|newrelic.license = ${NR_INSTALL_KEY}|g" /usr/local/etc/php/conf.d/newrelic.ini

cat > /usr/local/etc/php/conf.d/ext-opcache.ini << EOL
zend_extension=opcache.so
EOL

# Add in the production opcache configuration
#
# PHP-fpm will have to be reloaded everytime the PHP file change
if [ "${OPCACHE_PRODUCTION}" == "yes" ]; then
cat >> /usr/local/etc/php/conf.d/ext-opcache.ini << EOL
opcache.revalidate_freq=0
opcache.validate_timestamps=0
opcache.max_accelerated_files=4000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
EOL
fi

exec /usr/local/sbin/php-fpm
